name: Build app for windows
on:
  push:
    tags:
      - '*'
jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle package
        run: ./gradlew package

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/compose/binaries/main/msi/*.msi"
          token: ${{ secrets.GITHUB_TOKEN }}