name: Build app for windows
on:
  push:
    tags:
      - '*'
jobs:
  build-and-upload:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle package
        run: ./gradlew package

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: build/compose/binaries/main

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-result
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "msi/*.msi,dmg/*.dmg,deb/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}